### PR TITLE
Add nix dependencies to stack.yaml

### PR DESCRIPTION
**Pull request by chris-martin**
This enables building on NixOS with `stack --nix`!

### CODE REVIEW

**Comment by snoyberg** [comment]
Unfortunately this change breaks non-Nix usage of wai (see the Travis build failures). How about including the changes in a commented-out section of the stack.yaml file?

**Comment by chris-martin** [comment]
Whoops, I didn't think that section would make any difference unless Nix support was explictily enabled with `nix.enable` or the `--nix` flag. Is there really no better way to do that? :frowning:

**Comment by snoyberg** [comment]
Maybe you can set nix.enable to false?

**Comment by chris-martin** [comment]
Trying that, waiting on the build now.

**Comment by chris-martin** [comment]
Looks like that worked!

**Pull request merged**
