### PR TITLE
[Draft] Use newer ghc-prim functions for mhDigitToInt

### PR DESCRIPTION
**Pull request by danwdart**
This makes it compile on 9.2, but haven't checked earlier versions yet.

Before submitting your PR, check that you've:

- [ ] Bumped the version number
- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@danwdart How did you build `streaming-commons` and `memory`?  I think that they have the same issues. So, I cannot test `warp` yet.

**Comment by danwdart** [comment]
I have the following in my default.nix I used to build it:

```nix
{ 
  nixpkgs ? import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/master.tar.gz") {},
  compiler ? "ghc921"
} :
let
  gitignore = nixpkgs.nix-gitignore.gitignoreSourcePure [ ../.gitignore ];
  lib = nixpkgs.pkgs.haskell.lib;
  myHaskellPackages = nixpkgs.pkgs.haskell.packages.${compiler}.override {
    overrides = self: super: rec {
      warp = self.callCabal2nix "warp" (gitignore ./.) {};
      vault = lib.doJailbreak (super.vault);
      hedgehog = lib.doJailbreak super.hedgehog;
      tasty-hedgehog = lib.doJailbreak super.tasty-hedgehog;
      bsb-http-chunked = super.bsb-http-chunked.overrideDerivation(g: {
        # conflates String with ByteString
        doCheck = false;
      });
      network-byte-order = (lib.doJailbreak (self.callCabal2nix "network-byte-order" (builtins.fetchGit {
        url = "https://github.com/kazu-yamamoto/network-byte-order.git";
        rev = "3570bb3a1aeae36c241bbad97f0c4d22162a2a65";
      }) {})).overrideDerivation(g: {
        doCheck = false; # {..} without the extension enabled
      });
      iproute = lib.doJailbreak (self.callCabal2nix "iproute" (builtins.fetchGit {
        url = "https://github.com/kazu-yamamoto/iproute.git";
        rev = "f387a37e07a4074d8e2b912834d93b6628d0befd";
      }) {});
    };
  };
  shell = myHaskellPackages.shellFor {
    packages = p: [
      p.warp
    ];
    shellHook = ''
      gen-hie > hie.yaml
      for i in $(find -type f); do krank $i; done
    '';
    buildInputs = with nixpkgs; with haskellPackages; [
      apply-refact
      cabal-install
      ghcid
      hlint
      implicit-hie
      krank
      stan
      stylish-haskell
      weeder
    ];
    withHoogle = false;
  };
  exe = lib.justStaticExecutables (myHaskellPackages.warp);
in
{
  inherit shell;
  inherit exe;
  inherit myHaskellPackages;
  warp = myHaskellPackages.warp;
}
```

**Comment by fumieval** [comment]
I have a version of memory which tentatively supports GHC 9.2: https://github.com/fumieval/hs-memory/commit/7d385cecad6d496ab0dc079237ed133b5de43b2d

**Comment by kazu-yamamoto** [comment]
@fumieval Do you have cryptonite, too?

**Comment by kazu-yamamoto** [comment]
Oh, josephcsible has. I understand.

**Comment by kazu-yamamoto** [comment]
Closing in favor of #863.

**Pull request closed without merging**
