### PR TITLE
Gzip minimum

### PR DESCRIPTION
**Pull request by gregwebs**
This is on top of a couple commits from #451. Untested at the moment, I will test before merging, but wanted to get this PR up to see if it makes sense

### CODE REVIEW

**Comment by snoyberg** [comment]
I like, though as with #451, think we should just use [requestBodyLength](http://haddock.stackage.org/lts-3.9/wai-3.0.4.0/Network-Wai.html#v:requestBodyLength).

**Comment by gregwebs** [comment]
The change to gzipping is only for the response

**Comment by snoyberg** [comment]
Oh, got it. Alright, that makes more sense. Maybe it's worth including in the docs that `requestBodyLength` can handle the request header case?

**Comment by gregwebs** [comment]
closing in favor of #453

**Pull request closed without merging**
