### PR TITLE
Fixes warnings and bumped stack lts

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by snoyberg** [comment]
Looks like this fails with older LTSes.

**Comment by flip111** [comment]
What's the minimum LTS that needs to be supported ?

**Comment by snoyberg** [comment]
You can see the test failures at the end of this PR page. We're currently going back to LTS 11 and Cabal with GHC 8.2.2.

**Comment by flip111** [comment]
I don't know why these builds are timing out.

**Pull request merged**
