### PR TITLE
warp: removed dead code

### PR DESCRIPTION
**Pull request by soenkehahn**
Remove some unused code (and moved two functions from `src` to `test`).

### CODE REVIEW

**Comment by gregwebs** [comment]
should this be closed?

**Comment by soenkehahn** [comment]
Sorry, I missed the travis failures. I'll try to fix this.

**Comment by soenkehahn** [comment]
Travis is fixed now.

**Comment by gregwebs** [comment]
cool. I will let someone else that is familiar with warp merge this.

**Comment by snoyberg** [comment]
Looks OK to me. @kazu-yamamoto any objections?

**Comment by kazu-yamamoto** [comment]
Some of unused functions are intentionally left. I don't believe that we can simply merge this pull request. What I can do is remove unnecessary functions manually by checking the entire patch. But if I do it, I cannot preserve @soenkehahn's credit.

**Comment by soenkehahn** [comment]
Fine with me.

**Comment by kazu-yamamoto** [comment]
@soenkehahn Thanks.

Done in the above patch.

**Pull request closed without merging**
