### PR TITLE
warp: support blaze-builder >= 0.4

### PR DESCRIPTION
**Pull request by manny-fp**

### CODE REVIEW

**Comment by manny-fp** [comment]
Not thoroughly tested, but builds and passes tests with both blaze-builder 0.3.3.4 and 0.4.

**Comment by manny-fp** [comment]
I'll look into the Travis failure.

**Comment by manny-fp** [comment]
@snoyberg I haven't been able to reproduce this exact error locally, but I've gotten other package version-related errors from doctest.  I have no prior experience with doctest, but my guess is that it's not defining the same preprocessor macros as cabal does.

**Comment by kazu-yamamoto** [comment]
I cannot reproduce this doctest failure in my environment, either.
Which version of GHC is used in travis-ci?

@snoyberg It would be usefull if we add "ghc --version" and "cabal --version" to .`travis.yml`.

**Comment by snoyberg** [comment]
@kazu-yamamoto Added :)

**Comment by MaxGabriel** [comment]
We could setup Travis CI to use each of the GHC versions so that all of the supported versions are tested. Since each version would run on a separate travis instance it shouldn't add much time to the builds.

**Comment by kazu-yamamoto** [comment]
@snoyberg Thanks. GHC is 7.6.3. OK. I will look into the source of this problem.

**Comment by kazu-yamamoto** [comment]
@MaxGabriel It's awesome!

**Comment by kazu-yamamoto** [comment]
I cannot reproduce this doctest errors with any versions of GHC and any versions of Cabal. So, I'm going to give up.

**Comment by kazu-yamamoto** [comment]
I created warp repo solely and test it with travis. See this result: 

https://travis-ci.org/kazu-yamamoto/warp/builds/51978170

So, the doctest failure is specific to cabal-meta, I guess.

**Comment by kazu-yamamoto** [comment]
Cc: @gregwebs

**Comment by MaxGabriel** [comment]
@snoyberg Your latest commit to allow fast-logger 2.3.0 has doctests passing on GHC 7.6 and 7.8 btw https://travis-ci.org/yesodweb/wai/builds/52230990

**Comment by kazu-yamamoto** [comment]
Can anyone explain what happened?

**Comment by kazu-yamamoto** [comment]
The dependency of fast-logger to blaze-builder is the source of this problem, right?

**Comment by snoyberg** [comment]
I'm guessing it pulled in conflicting versions of dependencies.

@MaxGabriel Are you suggesting we roll back my commit that disabled the doctests by default? I'm fine with that.

**Comment by MaxGabriel** [comment]
@snoyberg yeah.

**Comment by kazu-yamamoto** [comment]
I think that we should merge the repoDocTestFailures branch.

**Comment by kazu-yamamoto** [comment]
Oh, that is #343! I agree to merge the pull request.

**Comment by MaxGabriel** [comment]
I made a new branch b/c the old one had some commit noise in it

**Comment by kazu-yamamoto** [comment]
Thank you for your excellent work!

**Pull request merged**
