### PR TITLE
Augment wai-extra package description.

### PR DESCRIPTION
**Pull request by creichert**
Resolves #298.

### CODE REVIEW

**Comment by snoyberg** [comment]
Does this actually add anything over the list of modules?

**Comment by creichert** [comment]
@snoyberg good point. I added some enhancements but I'm okay if this doesn't add anything over the module list and existing haddocks.

What is with the build failures? https://travis-ci.org/yesodweb/wai/builds/51985424#L1111

Does #338 fix that?

**Comment by snoyberg** [comment]
I'm tempted to disable the doctests on Travis, since they are very unreliable. @kazu-yamamoto any objection?

**Comment by snoyberg** [comment]
Generally speaking, I'm not thrilled about the concept of cabal file descriptions, due to the necessity of duplicating information with the README.md file. Hopefully Hackage will fix this issue soon (https://github.com/haskell/hackage-server/issues/262 and https://github.com/haskell/hackage-server/issues/279).

**Comment by creichert** [comment]
I agree. I primarily wanted to put the docs there for `wai-extra` since the complaint was specifically that they could not find the info.

Once the issue is fixed in Hackage I'll help move this directly to the README.md.

**Comment by snoyberg** [comment]
Awesome, thank you!

**Pull request merged**
