### PR TITLE
CI fix for recv package

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by Vlix** [comment]
It seems `recv` should be added to the build-dependecies of `warp.cabal`?

**Comment by kazu-yamamoto** [comment]
`warp.cabal` has `recv`.

**Comment by snoyberg** [comment]
It looks like the dep is missing for the benchmarks.

**Comment by Vlix** [comment]
> It looks like the dep is missing for the benchmarks.

Ah, indeed.

For reference:
```
warp                         > Building benchmark 'parser' for warp-3.3.23..
[...]
warp                         > [7 of 8] Compiling Network.Wai.Handler.Warp.Types
warp                         > 
warp                         > /home/runner/work/wai/wai/warp/Network/Wai/Handler/Warp/Types.hs:14:1: error:
warp                         >     Could not load module ‘Network.Socket.BufferPool’
warp                         >     It is a member of the hidden package ‘recv-0.0.0’.
```

**Pull request closed without merging**
