### PR TITLE
wai: add getRequestBodyChunk to silence requestBody deprecation warning

### PR DESCRIPTION
**Pull request by dbeacham**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by Vlix** [comment]
Thank you for the PR!

I think the name `setRequestBodyChunk` makes sense to be the opposite of `getRequestBodyChunk`, but you're not setting a chunk when using this setter, so I think just keeping it as `setRequestBody` might be better. Or maybe even `replaceRequestBody` :thinking:

**Comment by dbeacham** [comment]
Yeah - name could be better. `setRequestBodyChunks` is another alternative.

**Comment by kazu-yamamoto** [comment]
@Vlix This PR looks good to me. May I merge this as is?

**Comment by Vlix** [comment]
There should be an `@since` declaration, version bump and addition to the ChangeLog, no?

**Comment by dbeacham** [comment]
Yeah. I'll sort that out later today.

**Review by Vlix — APPROVED** [review]

**Comment by kazu-yamamoto** [comment]
Rebased and merged.
Thank you all for your contributions!

**Pull request closed without merging**
