### PR TITLE
warp, warp-tls: Export functions to serve applications over existing connections

### PR DESCRIPTION
**Pull request by dpwiz**
For #1006 

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Review by kazu-yamamoto — APPROVED** [review]
No objections though I don't understand the purpose completely.

**Comment by kazu-yamamoto** [comment]
Rebased and merged.
Thank you for your contribution.
If you wish, I will make new releases.

**Comment by dpwiz** [comment]
> No objections though I don't understand the purpose completely.

That's one of the legs for the TLS virtual hosts effort (with the other being that SNI thing).

> If you wish, I will make new releases.

Thanks! I'll be glad, but it isn't quite urgent.

**Comment by kazu-yamamoto** [comment]
New versions have been released.

**Pull request closed without merging**
