### PR TITLE
delete unnecessary isHead plumbing through RspFile

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This PR deletes what appears to be some unnecessary `isHead :: Bool` plumbing via the `RspFile` constructor.

Where the `isHead` field was referenced, we also have `method` in scope, from which `isHead` was originally derived. We can just use that.

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Looks like a CI fluke? It passed on everything except stack nightly Windows.

**Comment by kazu-yamamoto** [comment]
I restarted CI.

**Review by kazu-yamamoto — APPROVED** [review]
CI passed.
LGTM

**Comment by kazu-yamamoto** [comment]
Rebased and merged.
Thank you for your contribution!

**Comment by mitchellwrosen** [comment]
Thank you!

**Pull request closed without merging**
