### PR TITLE
Continue with the Sender loop despite closed streams

### PR DESCRIPTION
**Pull request by awpr**

### CODE REVIEW

**Comment by awpr** [comment]
Finally finished rebasing my changes onto the recent priority changes.  I added a hack to close all streams immediately and confirmed that without this change, this made the whole connection end, and with the change, the connection survived.

**Comment by awpr** [comment]
Context: my comment on #423

**Comment by awpr** [comment]
(the diff looks big, but it's basically just indenting a bunch of lines by 4 spaces and moving 'loop' outside of 'unlessClosed').

**Comment by creichert** [comment]
BTW, you can diff with no whitespace using the `w=1` query parameter. https://github.com/yesodweb/wai/pull/424/files?w=1

**Comment by creichert** [comment]
@awpr This is great stuff, thanks a lot

**Comment by kazu-yamamoto** [comment]
@awpr Please separate "layout change only" commits and other commits. If mixed, it's quite hard to review.

**Comment by kazu-yamamoto** [comment]
The point is that `loop` is the outside of `unlessClosed`, right?

**Comment by kazu-yamamoto** [comment]
@awpr Sorry for my previous comment. Your patch does not incude "layout change only".

**Comment by kazu-yamamoto** [comment]
Now I understand the patch completely. Again, sorry for my confusion.

**Comment by kazu-yamamoto** [comment]
A new version has been released.

**Pull request merged**
