### PR TITLE
Deprecation warning supression

### PR DESCRIPTION
**Pull request by akilegaspi**
This pull request primarily focuses on removing deprecated warnings so that the compiler logs makes more sense

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Since I didn't notice this PR, I has replaced `sClose` with `close` by myself.
I'm very sorry. 

What I can do is cherry-pick 9f5acc0. Is it OK for you?

**Comment by akilegaspi** [comment]
It's fine!

**Comment by snoyberg** [comment]
Have all changes been cherry picked?

**Comment by kazu-yamamoto** [comment]
@snoyberg Thank you for your remainder. I have done. Let's close.

**Pull request closed without merging**
