### PR TITLE
Fourmolu

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
- Adding `fourmolu.yaml`
- Reformatting most Haskell files with `fourmolu`

### CODE REVIEW

**Review by Vlix — APPROVED** [review]
Straight-forward addition 👍

The following is one of the reasons I prefer trailing function arrows, though:
```hs
-- leading
type CheckCreds =
    ByteString
    -> ByteString
    -> IO Bool
```
compare with trailing:
```hs
-- trailing
type CheckCreds =
    ByteString ->
    ByteString ->
    IO Bool
```
Since this way: they're alligned, and the one that stands out because it doesn't have an arrow is the result of the function, instead of the first argument. (My reasoning is, the first argument isn't special, the result is, so having that be more visually apparent makes more sense)

And with normal functions the diffs are nicer if the first argument moves:
```diff
  -- leading
  myFunc
-    :: Arg1
-    -> Arg2
+    :: Arg2
+    -> Arg1
     -> Result
```
versus
```diff
  -- trailing
  myFunc ::
-    Arg1 ->
     Arg2 ->
+    Arg1 ->
     Result
```

But if you prefer this, it's a nit-pick, so it's totally fine 👍
LGTM.

**Comment by kazu-yamamoto** [comment]
I have no logical reason why I prefer leading.
Anyway, I will merge this after all possible PRs have been merged.

**Comment by Vlix** [comment]
I'd say just add this in. 👍 
The other open PRs can resolve any conflicts without too much hassle. (only one with more hassle is mine, but I'll reformat it after, no problem)

**Comment by kazu-yamamoto** [comment]
I would like to merge #964 first.

**Comment by kazu-yamamoto** [comment]
Rebased and watching CI.

**Pull request merged**
