### PR TITLE
Getting rid of warnings and hlint suggestions

### PR DESCRIPTION
**Pull request by Vlix**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

---

Wanted to get rid of warnings you get when building the packages in this repo, so I tried to do so. And refactored some small stuff.

Only real "change" is adding `defaultGzipSettings` to hopefully at some point be able to phase out the `data-default` dependency `wai-extra` still has.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Is this ready for merging?

**Comment by Vlix** [comment]
If you feel the changes are acceptable, this is indeed ready for merging.

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged.

Off topic but if we could agree with a formatter, it would be great.
I'm using `fourmolu` recently.

**Comment by Vlix** [comment]
I've also always used `fourmolu`. Also just added it to the [`http-types`](https://github.com/Vlix/http-types) package I just took maintainership over. Shall I (when I have time) add the `fourmolu.yaml` and do a full formatting of the code base?

Do we want specific settings? I mostly go for very diff-able settings and readability. (4 spaces indent, half-indent `where`s)

**Comment by kazu-yamamoto** [comment]
My settings is here:

https://github.com/kazu-yamamoto/quic/blob/master/fourmolu.yaml

**Comment by kazu-yamamoto** [comment]
When we reach consensus, I will add `fourmolu.yaml` and format most HS files (without HS with CPP) and send a PR.

**Comment by kazu-yamamoto** [comment]
Closing in favor of #965.

**Pull request merged**
