### PR TITLE
Rethrow async exception

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
@Vlix This is the first step to fix the stuffs in #1012.

### CODE REVIEW

**Comment by Vlix** [comment]
I'm a bit busy this week, but will try to take a look next week :+1:

**Comment by kazu-yamamoto** [comment]
`time-manager` is leaked sometime:

1) In this pattern, `time-manager` is solely leaked:

```
20 QUIC dispatcher: ThreadBlocked BlockedOnSTM
24 WAI timeout manager (Reaper): ThreadBlocked BlockedOnMVar
3462 Warp HTTP/1.1 [::ffff:81.161.238.88]:53801: ThreadBlocked BlockedOnMVar
3464 Warp HTTP/1.1 [::ffff:81.161.238.88]:53803: ThreadBlocked BlockedOnMVar
3467 Warp HTTP/1.1 [::ffff:81.161.238.88]:53831: ThreadBlocked BlockedOnMVar
3570 Warp HTTP/1.1 [::ffff:81.161.238.88]:56968: ThreadBlocked BlockedOnMVar
3575 Warp HTTP/1.1 [::ffff:81.161.238.88]:57059: ThreadBlocked BlockedOnMVar
```

2) In this pattern, `time-manager` leaks other workers by holding `ThreadId`. I can tell this because they are in `ThreadFinished`. [af20093](https://github.com/yesodweb/wai/pull/1013/commits/af20093a4ca05851c6d65bdcfaf01398f01e1496) tries to fix this.

```
10150 WAI timeout manager (Reaper): ThreadBlocked BlockedOnMVar
10190 Warp HTTP/1.1 [::ffff:103.8.117.203]:43390: ThreadFinished
10191 Warp HTTP/1.1 [::ffff:103.8.117.203]:43392: ThreadFinished
10193 Warp HTTP/1.1 [::ffff:103.8.117.203]:43404: ThreadFinished
10202 Warp HTTP/1.1 [::ffff:103.8.117.203]:43406: ThreadFinished
10204 Warp HTTP/1.1 [::ffff:103.8.117.203]:41256: ThreadFinished
```

**Comment by kazu-yamamoto** [comment]
Both `Reaper` and `TimeManager` do not use `MVar` at all.
Why `BlockedOnMVar`?

**Comment by kazu-yamamoto** [comment]
I hope that 489c063 fixes the leak of TimeManager.

**Comment by kazu-yamamoto** [comment]
TimeManager is still leaking, sigh.

```
23 WAI timeout manager (Reaper): ThreadBlocked BlockedOnMVar
```

**Comment by kazu-yamamoto** [comment]
The 23 thread is gone. Why did it took so a long time?

**Comment by kazu-yamamoto** [comment]
I'm going to merge this PR and release new versions as this PR fixes some thread leaks.
Of course, comments after releasing are welcome.

**Comment by Vlix** [comment]
Few things I've found:

- `onException` in [`httpOverTLS`](https://github.com/yesodweb/wai/pull/1013/files#diff-6cf1a9e1c67495befea8722c388631b0ca958510e97d35feb145f0fd551001b4R358) is not masked, so the `close s` can be interrupted by any exception. (do we want that?)
- [this `catch` handler](https://github.com/yesodweb/wai/pull/1013/files#diff-41509cf4f3b5ec127214e7ac8f4266baae079012d091b1c4aad796a1509ac584R154) is interruptible now, is that ok?
- the [withFdCache](https://github.com/yesodweb/wai/commit/288e38fbdbe800b0250fbddf4bf5c6cec3d8a520#diff-b878b012e6eb4f62adacc9bd7bd3403bd4465ca3597c7b0946f68367ce404b85R51)'s `after` is now not `uninterruptibleMask`ed. Though I think that's probably fine?
- [getAndRegisterInfo](https://github.com/yesodweb/wai/commit/288e38fbdbe800b0250fbddf4bf5c6cec3d8a520#diff-2cf6b9401082fbc68092f73fb80921db6483546dd8f62b979a870af7eb4baa46R76) will now also catch `AsyncExceptions` and `negative` turns them into a syncronous `Exception`.
- this [terminate](https://github.com/yesodweb/wai/commit/288e38fbdbe800b0250fbddf4bf5c6cec3d8a520#diff-2cf6b9401082fbc68092f73fb80921db6483546dd8f62b979a870af7eb4baa46R102) will not be `uninterruptibleMask`ed. Is that ok? How important is `reaperStop`?
Same with this [`close`](https://github.com/yesodweb/wai/pull/1013/files#diff-f6863cde0b4e33012b8c901c00d5c2aab1a58f877bfdb2f159fcf11a6a148812R156), this [`stopManager`](https://github.com/yesodweb/wai/pull/1013/files#diff-f6863cde0b4e33012b8c901c00d5c2aab1a58f877bfdb2f159fcf11a6a148812R249), this [`cleanUp`](https://github.com/yesodweb/wai/pull/1013/files#diff-f6863cde0b4e33012b8c901c00d5c2aab1a58f877bfdb2f159fcf11a6a148812R349), this [`cancel`](https://github.com/yesodweb/wai/pull/1013/files#diff-f6863cde0b4e33012b8c901c00d5c2aab1a58f877bfdb2f159fcf11a6a148812R358), this [`onClose`](https://github.com/yesodweb/wai/pull/1013/files#diff-f6863cde0b4e33012b8c901c00d5c2aab1a58f877bfdb2f159fcf11a6a148812R366), this [`teardown`](https://github.com/yesodweb/wai/commit/288e38fbdbe800b0250fbddf4bf5c6cec3d8a520#diff-a99973a5a7daa09cb6dc205b62bdfe2d987a58eabe65e288c237ba73454fd478R121), this [`close`](https://github.com/yesodweb/wai/commit/288e38fbdbe800b0250fbddf4bf5c6cec3d8a520#diff-661039687bd94057e4af5b85146531f918b2258d92b44ef6e38a43098bf4807bR107)
- `time-manager` now seems to also eat up `AsyncException`s [here](https://github.com/yesodweb/wai/pull/1013/files#diff-1a39f65093b844d5c9b51b3d92d0297abc6e7a7c8812f2ec21381affe981a5fdR73) and [here](https://github.com/yesodweb/wai/pull/1013/files#diff-1a39f65093b844d5c9b51b3d92d0297abc6e7a7c8812f2ec21381affe981a5fdR88)

The difference between `uninterruptibleMask` and regular `mask` is only that `AsyncExceptions` can come through with `mask` in case the thread is blocked, right? Which would be when waiting for an `MVar`, or a `threadDelay` too? (I forgot how it goes with FFI calls :thinking:)

**Comment by kazu-yamamoto** [comment]
From the doc of `Control.Exception`:

> If the target thread is currently making a foreign call, then the exception will not be raised (and hence `throwTo` will not return) until the call has completed.

That is, asynchronous exceptions cannot interrupt foreign calls.

**Comment by kazu-yamamoto** [comment]
`ThreadId`s in auto-update are not disclosed.
Nobody can throw asynchronous exceptions to threads spawned by auto-update, I believe.

**Comment by Vlix** [comment]
> `ThreadId`s in auto-update are not disclosed. Nobody can throw asynchronous exceptions to threads spawned by auto-update, I believe.

`StackOverflow` and `HeapOverflow` are also asynchronous, so I don't think you'd want to assume anything (though the chances are super small)

**Comment by kazu-yamamoto** [comment]
> StackOverflow` and `HeapOverflow` are also asynchronous, so I don't think you'd want to assume anything (though the chances are super small)

Good point!
I will think your review results again.

**Comment by Vlix** [comment]
> OK. I understand. `threadDelay` is implemented with `MVar`. So, it can be in the `BlockedOnMVar` state. IOManager keeps working if connections come repeatedly. So, it can have a long life and is finished when all connections are finished. Now I think TimeManager is not leaking.

How did you figure this out, btw? I can only narrow it down to an internal built-in `delay#` function :thinking:

**Comment by kazu-yamamoto** [comment]
> How did you figure this out, btw? I can only narrow it down to an internal built-in `delay#` function :thinking:

See: https://www.stackage.org/haddock/lts-22.42/base-4.18.2.1/src/GHC.Conc.IO.html#threadDelay

Our RTS is `threaded`. So, we should follow `Event.threadDelay`

`ghc/libraries/base/GHC/Event/Thread.hs:threadDelay` is defined as follows:

```haskell
threadDelay :: Int -> IO ()
threadDelay usecs = mask_ $ do
  mgr <- getSystemTimerManager
  m <- newEmptyMVar
  reg <- TM.registerTimeout mgr usecs (putMVar m ())
  takeMVar m `onException` TM.unregisterTimeout mgr reg
```

**Pull request merged**
