### PR TITLE
Only conditionally produce HTTP 100 Continue

### PR DESCRIPTION
**Pull request by reiddraper**
Only produce HTTP 100 Continue if the application asks for the request
body. This allows the application to respond with a 4xx or 5xx status,
having only looked at the request headers, and never receiving the body.
An example use-case for this would be responding with HTTP 403 or 413,
without having to waste resources sending a large request body.

Addresses discussion in #186.

---

This is mostly a PR to start a discussion for now, as the behavior I've implemented is not (yet) behind a setting. This _could_ become the default behavior, but I wanted to start a discussion about this particular implementation, before getting into those details. Feedback appreciated.

### CODE REVIEW

**Comment by reiddraper** [comment]
cc @kazu-yamamoto

**Comment by snoyberg** [comment]
I haven't followed this discussion closely enough, but at an initial review, it seems like a good change in behavior that shouldn't break existing applications. I'm not sure we need to hide the behavior behind any flags. I'll defer to @kazu-yamamoto though, as he probably understands this better than I do.

**Comment by kazu-yamamoto** [comment]
LGTM. I have merged this patch with rebasing.

**Comment by kazu-yamamoto** [comment]
@reiddraper Please close this if everything is OK for you.

**Comment by reiddraper** [comment]
@kazu-yamamoto :+1:

**Pull request closed without merging**
