### PR TITLE
Add basic GHC 7.10 support to travis config

### PR DESCRIPTION
**Pull request by creichert**
Testing this out to help validating PRs

### CODE REVIEW

**Comment by creichert** [comment]
Weird issues with base and GHC 7.10 in the default Travis config. Going to try hvr's ppa.

**Comment by kazu-yamamoto** [comment]
Is this issue fixed? https://github.com/travis-ci/travis-ci/issues/3785

**Comment by MaxGabriel** [comment]
@kazu-yamamoto I don't think so, based on their docs.

**Comment by creichert** [comment]
I tried that initially. I should have squashed my commits. I ended up
going with the hvr ppa which also gives us room to experiment with
allowed_failure on ghc-HEAD and other release candidates.

**Pull request merged**
