### PR TITLE
wai/warp: Remove dependency on blaze-builder

### PR DESCRIPTION
**Pull request by sjakobi**
Before submitting your PR, check that you've:

- [X] Bumped the version number

After submitting your PR:

- [X] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by sjakobi** [comment]
This makes both libraries buildable with GHC-8.4.1. The warp testsuite doesn't build due to its dependency on http-client -> blaze-builder.

**Comment by kazu-yamamoto** [comment]
Relating to #682.

**Comment by sjakobi** [comment]
> Relating to #682.

Oops, I somehow missed that. At least the changes to warp should be unique.

**Comment by kazu-yamamoto** [comment]
Would you close this PR and join #682? :-)

**Comment by sjakobi** [comment]
Done! :)

**Pull request closed without merging**
