### PR TITLE
wai-app-static: make ssAddTrailingSlash work in combination with ssIn…

### PR DESCRIPTION
**Pull request by soenkehahn**
…dices

### CODE REVIEW

**Comment by soenkehahn** [comment]
Please don't merge yet, something seems to be wrong with `WaiAppStatic.Storage.Embedded.TH.mkSettings` now.

**Comment by soenkehahn** [comment]
Disregard my last comment. `mkSettings` has an unrelated problem.

**Comment by soenkehahn** [comment]
The travis failure seems unrelated...

**Comment by snoyberg** [comment]
Looks like there's a merge conflict with the previous PR, can you resolve?

**Comment by soenkehahn** [comment]
Of course. I'm on it.

**Comment by soenkehahn** [comment]
Rebased on `master`.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
