### PR TITLE
ensuring that GET and HEAD returns the same headers. (#354)

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
@DeathByTape @snoyberg Please review this patch.

### CODE REVIEW

**Comment by snoyberg** [comment]
@DeathByTape I think we need to modify the autohead middleware to keep the ResponseFile response if available.

@kazu-yamamoto I'm actually somewhat confused about the `isGet` stuff; isn't the point to check if it's *not* HEAD?

**Comment by kazu-yamamoto** [comment]
`isGet` means `isNotHead` in this case. Other methods are unsuitable here, I believe.

**Comment by snoyberg** [comment]
I may be reading this code incorrectly, but I thought the code path is simply for a response which is returning a `ResponseFile`. While a GET response is by far the most likely case for that, it seems reasonable that an application could similarly use a `ResponseFile` for a POST or PUT request if desired. Is there any downside to changing `isGet` to `isNotHead`?

**Comment by kazu-yamamoto** [comment]
I wanted to give a name of `hasBody` to this variable. But I did not since it is used already. 

I would avoid negative names for readability. Any suggestions? What about `useSendFile`?

**Comment by snoyberg** [comment]
How about `isHead` and make the test `not isHead`?

**Comment by kazu-yamamoto** [comment]
Is ed5afae what you want?

**Comment by DeathByTape** [comment]
I submitted #358 with some changes to the middleware (effectively neutralizes it) and update `wai-app-static` to handle this. It is a PR into this branch (get-head) since it all seems like a single feature to me. I can change the PR location to master, however, if that's better.

**Comment by kazu-yamamoto** [comment]
@snoyberg Please merge this pull request to master if you think OK.

**Comment by snoyberg** [comment]
Merged and released, thanks guys!

**Pull request merged**
