### PR TITLE
Recovering CI

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
Test purpose only. Do not merge now.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@snoyberg How should we modify stack.yaml files to pass CI when we extracted a new library?
I tried several things but no luck.

**Comment by snoyberg** [comment]
I got this to build locally by removing the extra-deps version in the stack.yaml:

```
-extra-deps:
-  - ./recv
```

The basic idea is that each package should appear exactly once, and for local packages in the monorepo you should put them under `packages` so that their test suites run. I can push another commit to your branch if you want, just let me know.

**Comment by kazu-yamamoto** [comment]
@snoyberg Please push your patch.

**Comment by snoyberg** [comment]
Check out #904. It doesn't pass, but I think those are legitimate failures. (Though we may want to drop lts-14.)

**Comment by kazu-yamamoto** [comment]
@snoyberg All tests except lts-14 passed. Since you want to drop lts-14, I dropped it. Are you OK to merge this PR to master?

**Comment by kazu-yamamoto** [comment]
@snoyberg @Vlix Thank you for your help!

**Pull request merged**
