### PR TITLE
Enable gzip compression when gzip is used

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by snoyberg** [comment]
What's the motivation behind making this change? There's a significant downside to always compressing files: it breaks the ability to use the sendfile optimization.

**Comment by psibi** [comment]
I think this is one of the way to fix #536. More details here: https://github.com/yesodweb/wai/issues/536#issuecomment-213684604

**Comment by snoyberg** [comment]
My understanding is that, right now:

* The default behavior is to not compress files
* There is an option available to compress files
* But the option available doesn't actually compress files

This PR changes the default behavior without fixing the fact that files are not compressed.

But I just realized from rereading the code that some assumptions over there are incorrect, I'll comment there.

**Comment by psibi** [comment]
Ok, my understanding was that the default behavior was to compress files. Probably we need to update the docs:

* http://www.yesodweb.com/book/web-application-interface#web-application-interface_middleware
* Hackage doc for `gzip` function

**Comment by snoyberg** [comment]
I'm in favor of updating the docs for clarity. Let's wait and see though that #536 is in fact resolved.

**Comment by psibi** [comment]
Closing the PR as #536 has been resolved.

**Pull request closed without merging**
