### PR TITLE
Linting and refactoring `wai-extra`

### PR DESCRIPTION
**Pull request by Vlix**
After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

----

## Review per commit

Refactored the gzip middleware to by DRY-er, added rethrowing of `Exception`s that can't come from this `Middleware`, tweaked adding of `Vary` header, made sure to always skip if response status is 206, and mainly:

### Added option to take the ETag header into account when caching zipped files

A few points why this is a WIP:
- I also removed the `Data.Default` dependency, probably as a relfex since it's useless (in my honest opinion), but I can revert that if necessary
- I'm not sure what kind of version bump this would be
- I still want to add some tests
- I want to add more documentation for the whole `Gzip` module
 
# EDIT: Changed this PR into just linting and refactoring

### CODE REVIEW

**Comment by snoyberg** [comment]
Would it be possible to separate out general code cleanup/reformatting changes from the meat of the change here?

**Comment by Vlix** [comment]
Just make two PRs you mean? Yeah, that should be possible.
Might close this one and make two new ones, we'll see.

**Comment by snoyberg** [comment]
Yes, two PRs would be better, thanks!

**Comment by Vlix** [comment]
Would you prefer me not to rip out the `Default` instance(s) for backwards compatibility? Or would it be ok te just get rid of `Data.Default` in its entirety? (This would probably be a somewhat breaking change 🤔 )

**Comment by snoyberg** [comment]
I'd rather avoid any breaking changes.

**Comment by Vlix** [comment]
Ok, removed all the functional changes, now this PR is just import linting, readability cleanup and refactors.

* [10377c3](https://github.com/yesodweb/wai/pull/875/commits/10377c3dc2dc6eb3b0b6cfa4faa4462827e58b59): mainly readability cleanup (redundant brackets, unnecessary `$`, avoid punning, etc)
* [c968a03](https://github.com/yesodweb/wai/pull/875/commits/c968a036248c281f09b4a6b4a5c2fec741e55b4e): **Most interesting commit; refactor of `gzip` middleware to keep it DRY, skip compression earlier, etc.**
* [25e5de5](https://github.com/yesodweb/wai/pull/875/commits/25e5de5b241ae6e63cf8292085d46847f4166679): linting imports and pragmas, more CPP around `import Applicative/Monoid` and some more readability cleanup

I also hanged two `data` into `newtype`, since they only had one constructor with one argument. I don't see how this could negatively impact anything, but if you do, I can revert those two.

**Comment by Vlix** [comment]
The one failing test is on Windows, and it fails on 1 test in `warp` because of an `IOException` where `sendbuf()` gets a wrong argument (I'm guessing the implementation is too Linux specific?)

**Comment by Vlix** [comment]
I don't feel this warrants an addition to the Changelog, right? So I feel this PR is done.
Especially as it's just the setup for the actual addition I'll put on top of this change after it's accepted.

**Review by snoyberg — APPROVED** [review]

**Pull request merged**
