### PR TITLE
Cleanly close connection when client closes connection prematurely

### PR DESCRIPTION
**Pull request by larskuhtz**
The function `Network.Socket.ByteString.recv` returns a `ByteString` of length zero when the connection has been closed.
The `mkConn` function does not handle that special case and instead calls `plainHTTP`, which raises a spurious `InsecureConnectionDemied` Exception. On the client side http-client-tls (and probably most other clients) reacts to this with an ungraceful connection reset.

This PR adds a new `ClientClosedConnectionPrematurely` constructor to `WarpTLSException`. When the client closes a connection immediately after the opening handshake and before the TLS "hello" message, the connection is gracefully closed and a `ClientClosedConnectionPrematurely` exception is raised.

Before submitting your PR, check that you've:

- [ ] Bumped the version number
- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by snoyberg** [comment]
@kazu-yamamoto this looks reasonable to me, but I think you'd be in a better position to review.

**Review by kazu-yamamoto — APPROVED** [review]
Looks excellent to me!

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!

**Comment by kazu-yamamoto** [comment]
A new version of warp-tls has been released.

**Pull request merged**
