### PR TITLE
Avoid sending an empty data frame after headers

### PR DESCRIPTION
**Pull request by awpr**
Previously the data frame header was always written and sent even if
zero bytes were available from the stream; now if zero bytes were
buffered, the data frame will not be sent.  This means we now need to
know whether the headers were already flushed, and possibly flush just
the headers after getting zero bytes of data.

Ameliorates #403.  (Empty data frames can still be sent by yielding a Builder for 0 bytes).

### CODE REVIEW

**Comment by awpr** [comment]
Good catch, that was wrong.  I fixed it, did some minor refactoring to make it clearer, and also added the same empty-data check to the case of continued streams.

**Comment by kazu-yamamoto** [comment]
Thanks. Merged with refactoring. Please check just in case.

**Comment by awpr** [comment]
Looks good.  I'm not a fan of that if-then-else layout, but it looks like that's the accepted style in this repo.

**Comment by kazu-yamamoto** [comment]
If you want to release a new version of Warp, I will.

**Comment by awpr** [comment]
I don't think this is urgent enough to warrant its own release.  The one client known to misbehave with empty data frames has also already been fixed.

**Pull request merged**
