### PR TITLE
845 async exceptions

### PR DESCRIPTION
**Pull request by snoyberg**
Before submitting your PR, check that you've:

- [X] Bumped the version number
- [X] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [X] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Review by kazu-yamamoto — CHANGES_REQUESTED** [review]
Wow. I understand how `unliftio` is well-designed. Tests on windows does not pass. Would you check it out?

**Comment by snoyberg** [comment]
> Wow. I understand how `unliftio` is well-designed. Tests on windows does not pass. Would you check it out?

Code fixed, tests seem to pass now. Would you be able to test off this fixes your original issue?

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged. Thank you!

**Pull request merged**
